/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EventManagementSystem;
import java.sql.*;

import javax.swing.JOptionPane;

/**
 *
 * @author Brij kishore sharma
 */
public class AddAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AddAdmin
     */
    public AddAdmin() {
        super("Add Admin");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jtf1 = new javax.swing.JTextField();
        jpf1 = new javax.swing.JPasswordField();
        jcbx = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 150));
        setMaximumSize(new java.awt.Dimension(600, 300));
        setMinimumSize(new java.awt.Dimension(600, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Admin Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 220, 45));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, 45));

        jButton1.setBackground(java.awt.SystemColor.activeCaption);
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Add admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 215, 189, 45));

        jButton2.setBackground(java.awt.SystemColor.activeCaption);
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 215, 189, 45));
        getContentPane().add(jtf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 38, 189, 45));
        getContentPane().add(jpf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 101, 189, 45));

        jcbx.setBackground(new java.awt.Color(153, 153, 0));
        jcbx.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        jcbx.setText("Show password");
        jcbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxActionPerformed(evt);
            }
        });
        getContentPane().add(jcbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 170, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventManagementSystem/images/Beautiful Landscape Wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name= jtf1.getText();
        String pass=jpf1.getText();
        try{
        connectionclass obj = new connectionclass();
        String q1="select * from admin where username ='"+name+"'";
//        int aa1 = obj.stn.executeUpdate(q1);
        ResultSet res= obj.stn.executeQuery(q1);
        if(res.next()){
        JOptionPane.showMessageDialog(null, "Please enter different username!");
        this.setVisible(true);
        }
        else{
        String q= "insert into admin(username,password) values('"+name+"','"+pass+"')";
        int aa = obj.stn.executeUpdate(q);
        if(aa==1){
            JOptionPane.showMessageDialog(null,"Your data inserted successfully");
            
            this.setVisible(true);
        }
        else{
        JOptionPane.showMessageDialog(null, "Please ! Enter carefully");
        this.setVisible(true);
        }
        }}
        catch(Exception ee){
        ee.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxActionPerformed
        // TODO add your handling code here:
        if(jcbx.isSelected()){
        jpf1.setEchoChar((char)0);
        }
        else{
        jpf1.setEchoChar('*');
        }
    }//GEN-LAST:event_jcbxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new EventManagementSystem().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jcbx;
    private javax.swing.JPasswordField jpf1;
    private javax.swing.JTextField jtf1;
    // End of variables declaration//GEN-END:variables
}
