/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EventManagementSystem;

import javax.swing.JOptionPane;
import java.sql.*;
//import javax.swing.JOptionPane;
import javax.swing.*;
/**
 *
 * @author Brij kishore sharma
 */
public class AddParticipants extends javax.swing.JFrame {

    /**
     * Creates new form participants
     */
    public AddParticipants() {
        super("ADD Participants");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        designationtf = new javax.swing.JTextField();
        nametf = new javax.swing.JTextField();
        numbertf = new javax.swing.JTextField();
        addata = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pidtf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 150));
        setMaximumSize(new java.awt.Dimension(700, 400));
        setMinimumSize(new java.awt.Dimension(700, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Name of Participant");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 250, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Designation");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 211, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 211, 30));
        getContentPane().add(designationtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 211, 30));

        nametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametfActionPerformed(evt);
            }
        });
        getContentPane().add(nametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 211, 30));
        getContentPane().add(numbertf, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 211, 30));

        addata.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addata.setText("Add to database ");
        addata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addataActionPerformed(evt);
            }
        });
        getContentPane().add(addata, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 235, 43));

        reset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 211, 43));

        cancel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 211, 43));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Event ID ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 211, 30));
        getContentPane().add(pidtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 211, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventManagementSystem/images/resize-16858791872020236856resize16858787311709174675JapanDigitalLandscapeHDWideWallpapersHDWallpapers.jpg"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addataActionPerformed
        // TODO add your handling code here:
        String name= nametf.getText();
        String designation=designationtf.getText();
        String phone_number= numbertf.getText();
        String pid= pidtf.getText();
        if(phone_number.length()==10){
        try{
        connectionclass obj = new connectionclass();
        String q1 = "SELECT 1 FROM events WHERE eid = '"+pid+"' LIMIT 1;";
//        int res= obj.stn.executeUpdate(q1);
        ResultSet res= obj.stn.executeQuery(q1);
        if(res.next()){
        String q= "insert into participants(pid,name,designation,mob_numb) values('"+pid+"','"+name+"','"+designation+"','"+phone_number+"')";
        int aa = obj.stn.executeUpdate(q);
        if(aa==1){
            designationtf.setText("");
            numbertf.setText(""); 
            nametf.setText("");
            pidtf.setText("");
            JOptionPane.showMessageDialog(null,"Your data inserted successfully"); 
           
            this.setVisible(true);
//            new participants().setVisible(true);
        }
        }
        else{
        JOptionPane.showMessageDialog(null, "Please ! Enter carefully");
        this.setVisible(true);
        }
        }
        catch(Exception ee){
        ee.printStackTrace();
        }}
        else {
        JOptionPane.showMessageDialog(null, "Number not in format ! Please Check ! ");
        }
    }//GEN-LAST:event_addataActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        nametf.setText("");
        designationtf.setText("");
        numbertf.setText("");
        pidtf.setText("");
        
    }//GEN-LAST:event_resetActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        new Eventsection().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void nametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddParticipants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddParticipants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddParticipants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddParticipants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new AddParticipants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addata;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField designationtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nametf;
    private javax.swing.JTextField numbertf;
    private javax.swing.JTextField pidtf;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
