/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EventManagementSystem;

import java.sql.*;
//import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
//import static jdk.dynalink.linker.support.Guards.isNull;

/**
 *
 * @author Brij kishore sharma
 */
public class ListofParticipants extends javax.swing.JFrame {
///*    String x[]={"Event id ","Name","Type of event","Venue","Date","Duration"};
//        String y[][]=new String[50][6];
//        int i=0,j=0;
//        JTable t1;*/
    /**
     * Creates new form OpenEvent
     */
    public ListofParticipants() {
        super("Open events");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        opbtn = new javax.swing.JButton();
        cnclbtn = new javax.swing.JButton();
        evtf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 150));
        setMaximumSize(new java.awt.Dimension(838, 474));
        setMinimumSize(new java.awt.Dimension(838, 474));
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Event ID");

        opbtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        opbtn.setText("Open");
        opbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opbtnActionPerformed(evt);
            }
        });

        cnclbtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cnclbtn.setText("Cancel");
        cnclbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnclbtnActionPerformed(evt);
            }
        });

        evtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evtfActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Participant ID", "Name of participants ", "Designation", "Phone number "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(evtf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(opbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(cnclbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cnclbtn, evtf, opbtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnclbtn)
                    .addComponent(opbtn)
                    .addComponent(evtf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cnclbtn, evtf, jLabel2, opbtn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnclbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnclbtnActionPerformed
        // TODO add your handling code here:
        new Eventsection().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cnclbtnActionPerformed

    private void opbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opbtnActionPerformed
        // TODO add your handling code here:
        String iid= evtf.getText();
        
        if(iid.isEmpty()){
         try {
        connectionclass obj = new connectionclass();
        String q1 = "SELECT * FROM participants ";
        ResultSet rest= obj.stn.executeQuery(q1);
        while (rest.next()){
            String pid = rest.getString("pid");
            String name = rest.getString("name");
            String desig = rest.getString("designation");
            String phnum = rest.getString("mob_numb");
            String tbData[]={pid,name,desig,phnum};
            DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
            //add string array data into table
            tbModel.addRow(tbData);
                    }
        }
        catch(Exception ee){
        ee.printStackTrace();
        }}
        else{
        try {
        int id;
            id = Integer.parseInt(iid);
        connectionclass obj = new connectionclass();
        
        if(id!=0){
        String q1 = "SELECT * FROM participants where pid = '"+id+"'";
        ResultSet rest= obj.stn.executeQuery(q1);
            while (rest.next()){
                String pid = rest.getString("pid");
                String name = rest.getString("name");
                String desig = rest.getString("designation");
                String phnum = rest.getString("mob_numb");
                String tbData[]={pid,name,desig,phnum};
                DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
                //add string array data into table
                tbModel.addRow(tbData);}}
        else{
        JOptionPane.showMessageDialog(null, "Enter correct ID.");
        }
        }
        catch(Exception ee){
        ee.printStackTrace();
        }
        }
        
        
        
        
        
        
        
//        try {
//        connectionclass obj = new connectionclass();
//        String q= "Select * from participants ";
//        ResultSet rest= obj.stn.executeQuery(q);
//        while (rest.next()){
//            y[i][j++]=rest.getString("eid");
//            y[i][j++]=rest.getString("name");
//            y[i][j++]=rest.getString("type_of_event");
//            y[i][j++]=rest.getString("venue");
//            y[i][j++]=rest.getString("date");
//            y[i][j++]=rest.getString("duration");
//            i++;
//            j=0;
////            String evid = String.valueOf(rest.getInt("eid"));//conversion due to int value 
////            String name = rest.getString("name");
////            String toe = rest.getString("type_of_event");
////            String venue = rest.getString("venue");
////            String date = rest.getString("date");
////            String duration = rest.getString("duration");
//            //string array for store data in jtable
////            String tbData[]={evid,name,toe,venue,date,duration};
////            DefaultTableModel tbModel = (DefaultTableModel)t1.getModel();
//            //add string array data into table
////            tbModel.addRow(tbData);
//                    }
//        t1=new JTable(y,x);
//        
//        }
//        catch(Exception ee){
//        ee.printStackTrace();
//        }
//        JScrollPane sp=new JScrollPane(t1);
//        add(sp);
    }//GEN-LAST:event_opbtnActionPerformed

    private void evtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evtfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListofParticipants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListofParticipants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListofParticipants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListofParticipants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new ListofParticipants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cnclbtn;
    private javax.swing.JTextField evtf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton opbtn;
    // End of variables declaration//GEN-END:variables
}
